[profile.default]
solc-version = '0.8.23'
src = 'contracts'
out = 'out'
test = 'test/foundry'
cache_path = 'cache/foundry'
libs = ["node_modules", "lib"]

remappings = [
    # Due to a misconfiguration of solidity-bytes-utils, an outdated version
    # of forge-std is being dragged in
    # 
    # To remedy this, we'll remap the ds-test and forge-std imports to ou own versions
    '@openzeppelin/=node_modules/@openzeppelin/',
    'splits-v2/=lib/splits-contracts-monorepo/packages/splits-v2/src',
]
